### ISSUE TITLE
Curious why this isn't in the WP repo?

### ISSUE THREAD

**Issue by thedonquixotic** [wp-sync-db/wp-sync-db#159]
I'm new to WP development so maybe there's a reason why this plug in isn't in the Wordpress plugin directory? Do they have a rule against database syncing plugins or something?

**Comment by thedonquixotic** [comment]
Ooooh I see. It's because it's a fork of WP Migrate Pro. Cool!

**Comment by asha23** [comment]
Yep. It's a snide copy

**Comment by thedonquixotic** [comment]
FOR FUTURE REFERENCE: I'd recommend the Outlandish fork which is actually maintained: https://github.com/outlandishideas/wp-sync-db
