### ISSUE TITLE
Failed migration due to different sql versions?

### ISSUE THREAD

**Issue by thedonquixotic** [wp-sync-db/wp-sync-db#160]
I know this is technically covered by #134 but it's been buried by other issues. Obviously this repo isn't being maintained, but thought that this issue in particular should be near the top in case someone was perusing the repo and knew how to fix it. 

Migration failed: unknown collation utf8mb4_unicode_520_ci

**Comment by asha23** [comment]
This is a common problem.

You should be able to fix it by doing a search replace for utf8mb4_unicode_520_ci and replacing that with utf8_unicode_ci

Then a find and replace on utf8mb4 and replace that with utf8

This is not a plugin issue it's a database compatibility issue

**Comment by thedonquixotic** [comment]
Depends on how you define "plugin issue".  I ain't complaining about a free
plugin that's obviously not been maintained.    One might argue though a
plugin that is capable to checking for this kind of server compatibility
error, should be able to fix and adjust itself accordingly. Robustness in
development.
