### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by asha23** [wp-sync-db/wp-sync-db#161]
Doesn't seem to work correctly on the latest version of PHP

**Comment by CHEWX** [comment]
@asha23 See — https://github.com/ggamel/wp-sync-db/commit/1fc6d203d8af0ff225326b2fb7db166112cb54e7 or https://github.com/wp-sync-db/wp-sync-db/issues/144

**Comment by CHEWX** [comment]
@asha23 No worries dude... !
