### ISSUE TITLE
don't want to sync pages

### ISSUE THREAD

**Issue by theo-69** [wp-sync-db/wp-sync-db#168]
Is it possible not to sync the pages table, tried it but then all pages were plank. Is it possible to combine table? If I only choose to sync some tables within terms all pages are erased.

**Comment by djboris88** [comment]
There is no such thing as 'pages table'. WP counts Pages as a post-type, and actually stores them in the `[prefix]_posts` table. If you have deselected this table, but failed to deselect `[prefix]_postmeta` table, you have overwritten all the meta fields you had stored for your Pages. In the `[prefix]_posts` table WP stores only the default fields like the Title, Content, Excerpt, Post Type, Author, Date...

So, to make sure you keep your Pages intact, you have to deselect two tables (possibly more, depending on any content builder plugins you have used), `[prefix]_posts` and `[prefix]_postmeta`. Note that this will also not copy content tied to any other post type, including media files! Unfortunately, this is how WP works, and it would require writing custom migration script to do a selective migration based on the content post type.

**Comment by theo-69** [comment]
okay thanks, than I will have to find another solution :-(
