### ISSUE TITLE
Does not correctly export SQL file

### ISSUE THREAD

**Issue by josiahwiebe** [wp-sync-db/wp-sync-db#23]
I'm trying to run this plugin on a local server (MAMP) and I'm not getting a proper database export.

Here's a dump of what I get:
```mysql
# WordPress MySQL database migration
#
# Generated: Thursday 22. January 2015 01:35 UTC
# Hostname: localhost
# Database: `foreverfamilies`
# --------------------------------------------------------

/*!40101 SET NAMES utf8 */;

SET sql_mode='NO_AUTO_VALUE_ON_ZERO';
```

Any thoughts?

**Comment by josiahwiebe** [comment]
Well, this is embarrassing. I think I solved the issue.

I disabled the Safari option "Open 'Safe Files' After Downloading" and it seemed to perform perfectly. Keep up the great work!

**Comment by twistedpixel** [comment]
You just saved my rear! Just thought I'd add a bit of detail in case anyone else in our situation arrives here (it applies to Wordpress MigrateDB and likely other sync plugins too). Safari's "Open safe files" includes gzipped files and these database sync plugins like to export the database compressed. When Safari tries to unzip it, it fails miserably and loses most of the file. Solution is - as Josiah says - disable the option in Safari prefs or disable gzipping of exported database.

**Comment by dallanlee** [comment]
This helped me too. I'm glad I came across this. Thanks!

**Comment by vincebrown** [comment]
Thank you , solved it for me as well!
