### ISSUE TITLE
Duplicated sites conflict

### ISSUE THREAD

**Issue by CraftyDevon** [wp-sync-db/wp-sync-db#30]
First off, thank you for this awesome plugin! I use it daily across our sites. I was curious as to whether or not you may have a solution to the following problem.

I use the WP-Duplicator plugin for initial site deployments since it makes things such a breeze. However, even though the URL changes (say, from mysite.dev to productionurl.com/sandbox to productionurl.com), the key remains the same, and I get the error "It appears you've entered the secret key for this website, you need to provide the secret key for the remote website instead." 

I've tried deleting the plugin and re-installing, but the same error appears. Is it possible to regenerate a unique key?

Thanks!

**Comment by slang800** [comment]
![screenshot from 2015-03-10 16 18 17](https://cloud.githubusercontent.com/assets/1049204/6584428/96497d18-c741-11e4-92aa-21c9c05d8634.png)

**Comment by CraftyDevon** [comment]
Well, that's a wee bit awkward....

Thank you!

**Comment by slang800** [comment]
no prob!
