### ISSUE TITLE
Pull migration - expecting JSON response but received empty for wp_posts 

### ISSUE THREAD

**Issue by runofthemill** [wp-sync-db/wp-sync-db#43]
Trying to pull from remote to local; getting the following error:
![screen shot 2015-05-29 at 11 56 23 am](https://cloud.githubusercontent.com/assets/8418440/7886800/6e7a77a4-05fa-11e5-836d-f6f5678e18fd.png)

Remote DB has posts in wp_posts - any ideas? Reset API key, verified push/pull settings on both source and destination, tables option is 'Migrate all tables with prefix "wp_"'

**Comment by RicCastelhano** [comment]
@runofthemill how did you solve this issue ? Im having the same one.

Thanks.

**Comment by runofthemill** [comment]
Ah this was so long ago...I can't really recall, but I'd try doing a db repair in mysql, or try a plugin like [WP Sweep](https://wordpress.org/plugins/wp-sweep/), then try again.
