### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by theMikeD** [wp-sync-db/wp-sync-db#47]
Is this being maintained with the current version of the source plugin, or is this an unmaintained version of an old release?

**Comment by slang800** [comment]
it's a bit behind the [delicious-brains branch](https://github.com/wp-sync-db/wp-sync-db/tree/delicious-brains), but it's still alive, and I'm accepting PRs to update it.

**Comment by mkormendy** [comment]
I'd say this ticket is closed.
