### ISSUE TITLE
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-' at line 1]

### ISSUE THREAD

**Issue by herrbischoff** [wp-sync-db/wp-sync-db#48]
I get the above error whenever I try to update my local dev environment with a remote installation.

The error log does not output anything except this:

```
site_url(): http://192.168.33.11/wp
home_url(): http://192.168.33.11
Table Prefix: wp_
WordPress: WP4.2.2
Web Server: Apache/2.4.7 (Ubuntu)
PHP: 5.5.9-1ubuntu4.9
MySQL: 5.5.43-MariaDB-1ubuntu0.14.04.2
ext/mysqli: yes
WP Memory Limit: 40M
WPSDB Bottleneck: 
Debug Mode: Yes
WP Max Upload Size: 
PHP Post Max Size: 
PHP Time Limit: 30
PHP Error Log: 
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled

Active Plugins:
Advanced Custom Fields Pro (v5.2.6) by elliot condon
Timber (v0.21.3) by Jared Novack + Upstatement
WP Sync DB (v1.5) by Sean Lang
```

Any idea how to solve this error?

**Comment by marcobarbosa** [comment]
I have the exact same error. Fresh install.

It only works when I do "Tables" > "Migrate only selected table below" and deselect "wp_options".

![screenshot 2015-07-07 15 43 02](https://cloud.githubusercontent.com/assets/61103/8547438/278b9948-24bf-11e5-95e8-4ed1cfed6e83.png)

**Comment by marcobarbosa** [comment]
Interestingly enough, exporting it to a file and importing works. So I assume there is nothing wrong with the data itself (this '-' that it complains about).

I don't mind debugging the code myself and potentially issuing a PR with a fix but I would appreciate some direction from the author here :)

**Comment by slang800** [comment]
I've never tested this on anything but MySQL, but I'd love to add support
for MariaDB. Feel free to PR.

**Comment by matlitel** [comment]
I have the same problem it was working fine at one point, i've tried everything but nothing solves the problem, anyone have an update?

**Comment by samirillian** [comment]
Same. Mine might correspond to the Wordpress 4.4 update, which changed some of the syntax in wp-options. Will let yall know if I figure out a fix.

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-' at line 1]

**Comment by herrbischoff** [comment]
@slang800: Seeing that this plugin was last updated on May 2015, is the project still active or considered as is?

**Comment by herrbischoff** [comment]
Closing this as there is apparently no interest of the author to fix this.

**Comment by ivcreative** [comment]
So is the author not updating this anymore?

**Comment by herrbischoff** [comment]
As the author is not responding to questions as to this project's future, I consider it stalled/dead. I have switched away from WordPress anyway, so no big loss for me. It's just too bloated — the Microsoft Word of CMS.

**Comment by ThriLLzd** [comment]
too bad. I just encountered this error with trellis / roots.io bedrock installation

**Comment by cbracco** [comment]
@ThriLLzd same 😕

**Comment by ThriLLzd** [comment]
@cbracco I went with https://github.com/valentinocossar/trellis-database-and-uploads-migration in the end as it is native to trellis. the issue that I had was that my ssh forwarding was not set up properly and I could not login into vagrant using ssh vagrant@myproject.dev. after this was set it worked. Maybe this somehow relates to your issues with db sync as others do not face it.

**Comment by IgorUsoltsev** [comment]
Hey all, I'm not sure if that will help someone but worked fine for me https://deliciousbrains.com/wp-migrate-db-pro/doc/error-sql-syntax/

**Comment by IgorUsoltsev** [comment]
I also found out that it may not work with older wp-sync-db version. Maybe you would need to update to 1.6 (https://github.com/corysimmons/wp-sync-db/archive/1.6.zip)

Taken from here [https://github.com/wp-sync-db/wp-sync-db/pull/142#issuecomment-321974301](url)

#142

**Comment by yratof** [comment]
The issue with this is that your database user doesn't have the correct permissions, ensure they have the privilege to GRANT
