### ISSUE TITLE
Invalid content verification signature, please verify the connection  (#124)

### ISSUE THREAD

**Issue by Lorenzbi** [wp-sync-db/wp-sync-db#54]
I am trying to pull/push but I always get an error. Invalid content verification signature, please verify the connection  (#124) I think it was 123 when pushing. I don't have modsecurity enabled, but am behind a reverse proxy.

Thanks

**Comment by rootion** [comment]
I keep having this message `"Invalid content verification signature, please verify the connection information on the remote site and try again. (#123)"` while pushing from localhost to live server. I don't have modsecurity enabled either. Any ideas of what's causing this?
