### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by sirhair** [wp-sync-db/wp-sync-db#55]
WordPress database error: [Can't find file: './cp_thenewe_com/_mig_wp_calebspitch_commentmeta.frm' (errno: 2)]
RENAME TABLE `_mig_wp_calebspitch_commentmeta` TO `wp_calebspitch_commentmeta`

---
I get the above error when I try to migrate for the first time... it doesn't matter if I select one or all tables, each table gives the same error.

Any Ideas?

I'm pushing from a localhost to a live server

**Comment by sirhair** [comment]
I found the problem. My local database was set to utf8mb4 while my remote could only accept utf8.
I had to convert my database [using this php code](http://stackoverflow.com/questions/29916610/1273-unknown-collation-utf8mb4-unicode-ci-cpanel) and configure my local wp-config to 
```
define('DB_CHARSET', 'utf8');
```

**Comment by slang800** [comment]
That's probably worth adding a check to wp-db-sync... we should give a better error than that.
