### ISSUE TITLE
Installing plugin using composer vs GitHubUpdater?

### ISSUE THREAD

**Issue by fahmad91** [wp-sync-db/wp-sync-db#57]
Hi, 

I noticed this plugin is configured to work with composer. My question is, whats the better approach to installing this plugin. Should we use GitHubUpdater (as recommended) or will composer work just as well? 

Currently I use composer to manage all the various plugins used by my wordpress site so I would prefer to use composer to install this plugin as well. Just wanted to get your opinion!

Thanks
Farhan

**Comment by mAAdhaTTah** [comment]
I use composer and it works well. There isn't really a difference, just whatever fits into your workflow.

**Comment by fahmad91** [comment]
@mAAdhaTTah Good to know! Thanks :)

**Comment by slang800** [comment]
I added GitHubUpdater because I didn't want to have to publish to the WordPress plugin site (it doesn't support git-tag based deployments)... There's nothing special about it - it was just the first thing I found that works - so you can use whatever you want.
