### ISSUE TITLE
How to pull from https to http

### ISSUE THREAD

**Issue by harryrook** [wp-sync-db/wp-sync-db#72]
Hi there, loving the program, and apologies if this is an obvious question I'm new to this. Is there any way to push and pull from https to http and visa versa, currently when I pull from https to http I get the https in the site which was previously http. Which isn't a major problem I can just change it in webfaction and then change it back, but a workaround would be preferable.

Also one more thing, I can never get it to push or pull plugins, is that normal?

Thanks for the great plugin

Best

Harry

**Comment by Freekbron** [comment]
You can prefix the find and replace input fields on the migrate page. Just replace '//' with 'https://' and ''http://''.

There is no option to pull and push plugins/files. Just the database.

**Comment by harryrook** [comment]
Ha ha of course, so obvious. Thank you very much for getting back to me, I see I thought that might be the case with plugins its no major problem ftping them. Thanks for the great plugin.

**Comment by slang800** [comment]
Closing because @Freekbron gave an excellent answer. Also pushing/pulling plugins sounds like an excellent addon... I'd totally support the creation of an addon to do that (even though I probably won't have time to do it myself).
