### ISSUE TITLE
Do you plan to integrate with WP-CLI ?

### ISSUE THREAD

**Issue by shulard** [wp-sync-db/wp-sync-db#82]
Hello !

I currently try to automate most of my WordPress tasks and it seems that your plugin fit my needs. It could be awesome to integrate with WP-CLI to perform full automation in command line.

What do you think ?

**Comment by mAAdhaTTah** [comment]
Already done: https://github.com/wp-sync-db/wp-sync-db-cli

**Comment by shulard** [comment]
Very nice, didn't though to look in another repo :+1:
