### ISSUE TITLE
Invalid nonce for: verify-connection-to-remote-site

### ISSUE THREAD

**Issue by senlin** [wp-sync-db/wp-sync-db#87]
Trying to push local database to staging site and getting this error when filling in the connection details. Therefore cannot connect.

Maybe has to do with the fact that staging site runs on SSL?

I don't know, never before had this issue.

**Comment by cullylarson** [comment]
I'm having the same problem. Trying to push, getting this error: `Invalid nonce for: verify-connection-to-remote-site`

**Comment by jajouka79** [comment]
im having this problem too, i'm using wp 4.9.4 and wp-migrate-pro 1.8.1

**Comment by jajouka79** [comment]
this error renders this plugin and its addons unusable

**Comment by cullylarson** [comment]
@jajouka79 I think I remember figuring out that this was an issue with `curl` connecting to the remote host. I believe it was actually a server issue (I could reproduce it with manual `curl` requests). It was on a host I didn't have control over, so couldn't restart, but it just fixed itself a few hours later. If you do have control of your server, try restarting it.

**Comment by cullylarson** [comment]
I'm getting this same error again. It looks like it's stemming from an incomplete migration, or some kind of "Bad Request" at the very end of the migration. Maybe it puts the plugin in a weird state?

Wordpress: 5.0.3
Migrate DB Pro: 1.9.2

**Comment by senlin** [comment]
plugin clearly is abandoned, so better fork out money for the real thing or do it manually

**Comment by cullylarson** [comment]
Oh, I was under the impression that this was the repo for the pro plugin. I'll post the issue somewhere else.
