### ISSUE TITLE
Excluded post types are deleted during migration.

### ISSUE THREAD

**Issue by msfragala** [wp-sync-db/wp-sync-db#99]
Pulling the `wp_posts` table from a remote database seems to delete the posts for any excluded post type. I'm unsure if this is a bug or just part of the package, but excluded post types should be completely untouched by the migration.

For instance, I have three custom post types for a client to make posts for on a staging environment. Our intent is to pull the posts for those post types to use in development, but leave other posts and pages untouched on our local environments.

**Comment by JanikWeb** [comment]
Must be a bug, this can't be intended... I also just discovered this (mis)behaviour.

**Comment by Spark3000** [comment]
+1
Wanting to add more posts to a custom post type on local and push to live when complete **_without_** deleting the posts in that post type which already exist on live. 

If this is expected behaviour then surely this setting must be renamed _Delete Posts in Post Type_ and I don't see how that would be very useful.

**Comment by janbarendse** [comment]
not doing what it was supposed anymore (with regards to CPT's)

**Comment by lisamarie2000** [comment]
+1

**Comment by glynnis** [comment]
+1!

I have a site with multiple custom post types, and occasionally I only want to pull one of those types when users of the site have made an update on Production and I want that to be reflected in my local environment.

Currently if I "exclude" post types I don't want to migrate when pulling, it deletes all the posts in it. Surely it is supposed to exclude the posts, as in not alter them.

**Comment by Martinhessmann** [comment]
+1

**Comment by MarcelSchulz** [comment]
+1

**Comment by webarktech** [comment]
+1 (million)

This is a 4 year old thread, are Delicious Brains even reading this?

**Comment by notslang** [comment]
@webarktech - Delicious Brains has nothing to do with this project. They aren't going to see this thread.

**Comment by jameshrp** [comment]
@notslang oh, so this is a fork with making some fixes. After building my entire SDLC process thinking that they had this capability, I just hit this blocker. Can't believe WP migrate doesn't offer this. @webarktech did you figure out a way around it?
